# Generated by Django 2.2.5 on 2019-10-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='sequence_type',
        ),
    ]
