# Generated by Django 3.0.8 on 2020-07-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nifti',
            options={'ordering': ('-id',), 'verbose_name': 'NIfTI'},
        ),
    ]
