# Generated by Django 2.2 on 2019-06-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='subject',
        ),
    ]
