# Generated by Django 2.2 on 2019-05-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequencetype',
            options={'ordering': ('title',)},
        ),
    ]
