# Generated by Django 2.2 on 2019-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='comments',
            field=models.TextField(blank=True, help_text='If anything noteworthy happened during acquisition, it may be noted here.', max_length=1000, null=True),
        ),
    ]
