# Generated by Django 2.2.8 on 2020-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nifti',
            name='path',
            field=models.FilePathField(max_length=1000, unique=True),
        ),
    ]
