# Generated by Django 3.0.6 on 2020-07-14 05:04

from django.db import migrations


class Migration(migrations.Migration):
    def sequence_type_to_definition(apps, schema_editor):
        SequenceType = apps.get_model("django_mri", "SequenceType")
        SequenceTypeDefinition = apps.get_model("django_mri", "SequenceTypeDefinition")
        for seq in SequenceType.objects.all():
            sequence_definition, _ = SequenceTypeDefinition.objects.get_or_create(
                sequence_variant=seq.sequence_variant,
                scanning_sequence=seq.scanning_sequence,
            )
            sequence_definition.sequence_type = seq
            sequence_definition.save()

    def definition_to_sequence_type(apps, schema_editor):
        SequenceType = apps.get_model("django_mri", "SequenceType")
        for seq in SequenceType.objects.all():
            sequence_definitions = seq.sequence_definition_set
            if len(sequence_definitions) > 1:
                for seq_definition in sequence_definitions.all():
                    SequenceType.objects.get_or_create(
                        title=seq_definition.title,
                        sequence_variant=seq_definition.sequence_variant,
                        scanning_sequence=seq_definition.scanning_sequence,
                    )
            else:
                seq_definition = sequence_definitions.first()
                seq.title = seq_definition.title
                seq.scanning_sequence = seq_definition.scanning_sequence
                seq.sequence_variant = seq_definition.sequence_variant
                seq.save()

    dependencies = [
        ("django_mri", "0002_auto_20200714_0504"),
    ]

    operations = [
        migrations.RunPython(
            sequence_type_to_definition, reverse_code=definition_to_sequence_type
        ),
        migrations.AlterUniqueTogether(name="sequencetype", unique_together=set(),),
        migrations.RemoveField(model_name="sequencetype", name="scanning_sequence",),
        migrations.RemoveField(model_name="sequencetype", name="sequence_variant",),
    ]
