# Generated by Django 2.2 on 2019-05-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0002_auto_20190430_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='_nifti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_mri.NIfTI'),
        ),
    ]
