# Generated by Django 2.2.12 on 2020-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0002_auto_20200202_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name_plural': 'MRI Scans'},
        ),
    ]
