# Generated by Django 2.2 on 2019-06-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0002_remove_scan_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='_nifti',
            new_name='nifti',
        ),
    ]
