# Generated by Django 2.2 on 2019-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_group'),
        ('django_mri', '0002_auto_20190528_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='study_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='mri_scans', to='research.Group'),
        ),
    ]
