# Generated by Django 2.2 on 2019-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0003_scan_study_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='study_groups',
            field=models.ManyToManyField(blank=True, related_name='mri_scans', to='research.Group'),
        ),
    ]
