# Generated by Django 2.2 on 2019-05-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('django_mri', '0003_auto_20190512_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='scan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mri_scans', to='research.Subject'),
        ),
    ]
