# Generated by Django 2.2 on 2019-06-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190625_1044'),
        ('django_mri', '0003_auto_20190628_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mri_scans', to='research.Subject'),
        ),
    ]
