# Generated by Django 3.0.6 on 2020-05-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0003_auto_20200425_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nifti',
            options={'verbose_name': 'NIfTI'},
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='nifti',
            new_name='_nifti',
        ),
    ]
