# Generated by Django 3.0.6 on 2020-07-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0003_auto_20200714_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequencetypedefinition',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='sequencetypedefinition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sequencetypedefinition',
            name='title',
        ),
    ]
