# Generated by Django 3.0.6 on 2020-05-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0007_inputdefinition_value_attribute'),
        ('django_mri', '0004_auto_20200512_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analyses.InputDefinition')),
            ],
            bases=('django_analyses.inputdefinition',),
        ),
        migrations.CreateModel(
            name='ScanInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analyses.Input')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_set', to='django_mri.ScanInputDefinition')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_input_set', to='django_mri.Scan')),
            ],
            bases=('django_analyses.input',),
        ),
    ]
