# Generated by Django 2.2 on 2019-05-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0004_auto_20190517_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='institution_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
