# Generated by Django 3.0.6 on 2020-05-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0006_niftiinput_niftiinputdefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nifti',
            name='parent',
        ),
    ]
