# Generated by Django 3.0.6 on 2020-08-13 01:18
import datetime

from django.db import IntegrityError, migrations
from django_mri.utils.utils import get_subject_model
from dicom_parser.header import Header as DicomHeader


class Migration(migrations.Migration):
    def scan_subject_to_session(apps, schema_editor):
        Subject = get_subject_model()
        Scan = apps.get_model("django_mri", "Scan")
        Session = apps.get_model("django_mri", "Session")

        for scan in Scan.objects.all():
            subject = Subject.objects.filter(
                id_number=scan.dicom.patient.uid
            ).first()
            first_image = scan.dicom.image_set.first().dcm.path
            header = DicomHeader(first_image)
            date = header.get("StudyDate") or header.get("SeriesDate")
            time = header.get("StudyTime") or datetime.time()
            session_time = datetime.datetime.combine(date, time)
            if not subject:
                session = Session.objects.create(time=session_time)
                scan.session_id = session.id
            else:
                session = subject.mri_session_set.filter(
                    time=session_time
                ).first()
                if not session:
                    session = Session.objects.create(
                        subject_id=subject.id, time=session_time
                    )
                scan.session_id = session.id
            try:
                scan.save()
            except IntegrityError:
                session = Session.objects.create(
                    subject_id=subject.id, time=session_time
                )
                scan.session_id = session.id
                scan.save()

    def session_to_scan_subject(apps, schema_editor):
        Scan = apps.get_model("django_mri", "Scan")
        for scan in Scan.objects.all():
            scan.subject = scan.session.subject
            scan.save()

    dependencies = [("django_mri", "0006_auto_20200813_0118")]

    operations = [
        migrations.RunPython(
            scan_subject_to_session, reverse_code=session_to_scan_subject
        ),
    ]
