# Generated by Django 3.0.6 on 2020-08-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_mri", "0007_migrate_subject_to_session"),
    ]

    operations = [
        migrations.RemoveField(model_name="scan", name="subject",),
    ]
