# Generated by Django 3.0.6 on 2020-05-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0007_inputdefinition_value_attribute'),
        ('django_mri', '0007_remove_nifti_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiftiOutputDefinition',
            fields=[
                ('outputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analyses.OutputDefinition')),
            ],
            bases=('django_analyses.outputdefinition',),
        ),
        migrations.CreateModel(
            name='NiftiOutput',
            fields=[
                ('output_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analyses.Output')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_set', to='django_mri.NiftiOutputDefinition')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_output_set', to='django_mri.NIfTI')),
            ],
            bases=('django_analyses.output',),
        ),
    ]
