# Generated by Django 3.0.6 on 2020-09-27 04:14

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.MEASUREMENT_MODEL),
        ("django_mri", "0008_auto_20200827_0229"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="measurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mri_session_set",
                to=settings.MEASUREMENT_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session", name="time", field=models.DateTimeField(),
        ),
    ]
