# Generated by Django 3.0.7 on 2020-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0008_auto_20200827_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
