# Generated by Django 3.1.3 on 2020-11-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0010_datadirectory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadirectory',
            options={'verbose_name_plural': 'Data Directories'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': 'modified'},
        ),
    ]
