# Generated by Django 3.1.3 on 2020-11-25 15:33

import django_mri.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0011_auto_20201115_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadirectory',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=django_mri.utils.utils.get_data_share_root),
        ),
    ]
