# Generated by Django 3.1.3 on 2020-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0012_auto_20201125_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadirectory',
            name='known_subdirectories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
