# Generated by Django 3.1.3 on 2020-12-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0013_auto_20201125_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrbApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=128, null=True)),
                ('number', models.CharField(max_length=32)),
                ('document', models.FileField(blank=True, max_length=1000, null=True, upload_to='mri/irb/')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='irb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_mri.irbapproval'),
        ),
    ]
