# Generated by Django 3.1.3 on 2020-12-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0014_auto_20201213_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irbapproval',
            options={'verbose_name': 'IRB Approval'},
        ),
    ]
