# Generated by Django 3.1.3 on 2021-01-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0015_auto_20201229_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ('-time',), 'verbose_name_plural': 'Scans'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-time',)},
        ),
    ]
