# Generated by Django 3.1.3 on 2021-03-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0016_auto_20210104_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ('-time',)},
        ),
    ]
