# Generated by Django 3.2 on 2021-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_auto_20210420_1608"),
        ("django_mri", "0018_auto_20210420_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="study_groups",
            field=models.ManyToManyField(
                blank=True, related_name="mri_scan_set", to="research.Group"
            ),
        ),
    ]
