# Generated by Django 3.2.3 on 2021-06-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201018_1638'),
        ('django_mri', '0019_alter_scan_study_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mri_session_set', to='accounts.laboratory'),
        ),
    ]
