# Generated by Django 3.2.6 on 2021-10-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0019_alter_scan_study_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequencetypedefinition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sequencetypedefinition',
            name='sequence_type',
        ),
        migrations.DeleteModel(
            name='SequenceType',
        ),
        migrations.DeleteModel(
            name='SequenceTypeDefinition',
        ),
    ]
