# Generated by Django 3.2.6 on 2021-11-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0020_auto_20211031_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifti',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivative_set', to='django_mri.nifti'),
        ),
    ]
