# Generated by Django 3.2.6 on 2022-03-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0014_auto_20220130_1027'),
        ('django_mri', '0021_nifti_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this atlas.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of this atlas.', null=True)),
                ('symmetric', models.BooleanField(default=True, help_text='Whether this atlas is symmetric or not.')),
            ],
            options={
                'verbose_name_plural': 'Atlases',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='A title for this metric.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text="A description of this metric's meaning and significance.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemisphere', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], help_text='The hemisphere in which this region is defined.', max_length=1, null=True)),
                ('title', models.CharField(blank=True, help_text='A title describing this region.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='A description of this region.', null=True)),
                ('index', models.PositiveIntegerField(blank=True, help_text='The index of this region within the atlas.', null=True)),
                ('subcortical', models.BooleanField(blank=True, default=False, help_text='Whether this region is subcortical or not.', null=True)),
                ('atlas', models.ForeignKey(help_text='The atlas in which the region is defined.', on_delete=django.db.models.deletion.CASCADE, to='django_mri.atlas')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Calculated score value.')),
                ('metric', models.ForeignKey(help_text='The metric represented by this score.', on_delete=django.db.models.deletion.CASCADE, to='django_mri.metric')),
                ('region', models.ForeignKey(help_text='The brain region for which this score was calculated.', on_delete=django.db.models.deletion.CASCADE, to='django_mri.region')),
                ('run', models.ForeignKey(help_text='The run from which this score was exrtacted.', on_delete=django.db.models.deletion.CASCADE, to='django_analyses.run')),
            ],
        ),
    ]
