# Generated by Django 3.2.6 on 2022-02-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_analyses", "0014_auto_20220130_1027"),
        ("django_mri", "0021_nifti_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atlas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of this brain atlas.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information about the atlas, references, how it was created, etc.",
                        null=True,
                    ),
                ),
                (
                    "symmetric",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this atlas' regions are symmetric or not.",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Atlases"},
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The name of the metric.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="How to metric is calculated, what is might represent, etc.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hemisphere",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Left"), ("R", "Right")],
                        help_text="The cerebral hemisphere in which the region is found (left or right), if it is a part of the cerebrum.",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The name of the brain region.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information about this brain region.",
                        null=True,
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="An atlas index associated with this region.",
                        null=True,
                    ),
                ),
                (
                    "subcortical",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Whether this region is subcortical or not.",
                        null=True,
                    ),
                ),
                (
                    "atlas",
                    models.ForeignKey(
                        help_text="The atlas in which this brain region is defined.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_mri.atlas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="The metric's value calculated in the associated run for the given region."
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        help_text="The metric represented by the value.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_mri.metric",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="The brain region for which the metric score was calculated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_mri.region",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="The run instance from which the metric was extracted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_analyses.run",
                    ),
                ),
            ],
        ),
    ]
