# Generated by Django 3.2.6 on 2022-03-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mri', '0022_atlas_metric_region_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='origin',
            field=models.ManyToManyField(help_text='The scan or scans from which this score was derived.', to='django_mri.Scan'),
        ),
        migrations.AlterField(
            model_name='score',
            name='region',
            field=models.ForeignKey(blank=True, help_text='The brain region for which this score was calculated.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mri.region'),
        ),
    ]
