"""
Logs text for the :mod:`~django_mri.utils` module.
"""
BUILD_BIDS_PATH_START: str = "Building BIDS-compatible path for scan #{scan_id}..."
NO_BIDS_PATH: str = "BIDS path could not be derived from scan #{scan_id}'s ({description}) parameters."
NAIVE_BIDS: str = "Naive relative path generated by dicom_parser based on DICOM metadata: {relative_path}"
SUBJECT_FIX: str = "Replacing Patient ID ({patient_id}) with subject primary key ({subject_id})..."
SINGLE_RUN_DESTINATION: str = "BIDS destination for scan #{scan_id} is: {destination}"
# flake8: noqa: E501
