spm('defaults', 'fmri');
spm_jobman('initcfg');
matlabbatch{1}.spm.tools.cat.estwrite.data = {'$DATA_PATH,1'};
matlabbatch{1}.spm.tools.cat.estwrite.nproc = $N_PROCESSES;
matlabbatch{1}.spm.tools.cat.estwrite.opts.tpm = {'$TPM_PATH'};
matlabbatch{1}.spm.tools.cat.estwrite.opts.affreg = '$AFFINE_REGULARISATION';
matlabbatch{1}.spm.tools.cat.estwrite.opts.biasstr = $BIAS_STRENGTH;
matlabbatch{1}.spm.tools.cat.estwrite.opts.accstr = $ACCURACY;
matlabbatch{1}.spm.tools.cat.estwrite.extopts.APP = $AFFINE_PREPROCESSING;
matlabbatch{1}.spm.tools.cat.estwrite.extopts.LASstr = $LOCAL_ADAPTIVE_SEGMENTATION_STRENGTH;
matlabbatch{1}.spm.tools.cat.estwrite.extopts.gcutstr = $SKULL_STRIPPING;
matlabbatch{1}.spm.tools.cat.estwrite.extopts.registration.dartel.darteltpm = {'$DARTEL_TEMPLATE_PATH'};
matlabbatch{1}.spm.tools.cat.estwrite.extopts.vox = $NORMALIZED_IMAGE_VOXEL_SIZE;
matlabbatch{1}.spm.tools.cat.estwrite.extopts.restypes.fixed = [$INTERNAL_RESAMPLING 0.1];
matlabbatch{1}.spm.tools.cat.estwrite.output.surface = $SURFACE_ESTIMATION;
matlabbatch{1}.spm.tools.cat.estwrite.output.ROImenu.atlases.neuromorphometrics = $NEUROMORPHOMETRICS;
matlabbatch{1}.spm.tools.cat.estwrite.output.ROImenu.atlases.lpba40 = $LPBA40;
matlabbatch{1}.spm.tools.cat.estwrite.output.ROImenu.atlases.cobra = $COBRA;
matlabbatch{1}.spm.tools.cat.estwrite.output.ROImenu.atlases.hammers = $HAMMERS;
matlabbatch{1}.spm.tools.cat.estwrite.output.GM.native = $NATIVE_GREY_MATTER;
matlabbatch{1}.spm.tools.cat.estwrite.output.GM.mod = $MODULATED_GREY_MATTER;
matlabbatch{1}.spm.tools.cat.estwrite.output.GM.dartel = $DARTEL_GREY_MATTER;
matlabbatch{1}.spm.tools.cat.estwrite.output.WM.native = $NATIVE_WHITE_MATTER;
matlabbatch{1}.spm.tools.cat.estwrite.output.WM.mod = $MODULATED_WHITE_MATTER;
matlabbatch{1}.spm.tools.cat.estwrite.output.WM.dartel = $DARTEL_WHITE_MATTER;
matlabbatch{1}.spm.tools.cat.estwrite.output.labelnative = $NATIVE_PVE;
matlabbatch{1}.spm.tools.cat.estwrite.output.bias.warped = $WARPED_IMAGE;
matlabbatch{1}.spm.tools.cat.estwrite.output.jacobianwarped = $JACOBIAN_DETERMINANT;
matlabbatch{1}.spm.tools.cat.estwrite.output.warps = $DEFORMATION_FIELDS;
spm_jobman('run', matlabbatch);
